### PR TITLE
Fix for #11 and rubocop warnings

### PR DESCRIPTION
**Pull request by zhulik**

### CODE REVIEW

**Comment by mcrosson** [comment]
This isn't strictly necessary

{{ content | markdownify }} will solve the issue of markdown not being rendered by the plugin

**Comment by abemedia** [comment]
Hi @zhulik, thanks for your contribution and sorry for keeping it waiting. Looks good but will manually test this before merging in. Will be merged in by the weekend.

**Comment by mcrosson** [comment]
@abeMedia I ran into troubles with custom PDF headers/footers with this branch.

The page.render() call seems to be causing it to use the HTML version of the page rather than any local adjustments for header/footer.

**Comment by abemedia** [comment]
I noticed you're using `page.render`, rather than `self.render`. Maybe something to do with that? (just a wild guess without going into detail)

**Pull request closed without merging**
